Add new model DiagnosisItem and add validations for Patient, Physician models
mariadenadel/Internship pull request #2
Opened 2021-12-15 15:59 UTC by mariadenadel

2021-12-15 18:59 UTC, olehvavryniv requested changes

2021-12-15 18:59 UTC, olehvavryniv commented on rails-homework/app/models/patient.rb
> +  validates :age, presence: true, numericality: { only_integer: true, greater_than: 0 }
What about age - 199 years? Is it valid?

2021-12-15 18:59 UTC, olehvavryniv commented on rails-homework/app/models/patient.rb
> +  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "enter valid email" }
What about first name and last name validations?

2021-12-15 18:59 UTC, olehvavryniv commented on rails-homework/db/migrate/20211215131353_change_patients_physicians_tables_and_add_new_diagnosis_items_table.rb
> +      t.string :email
Please add NOT NULL constraints.

2021-12-16 16:21 UTC, olehvavryniv approved these changes

2021-12-16 16:25 UTC, Alice932 approved these changes

2021-12-16 16:26 UTC, merged